# Generated by Django 4.0 on 2022-01-04 20:14

from django.db import migrations


def fill_db(apps, schema_editor):
    Teacher = apps.get_model("data", "Teacher")
    teacher_1 = Teacher.objects.create(first_name="Daniil", last_name="Shadrin")
    teacher_2 = Teacher.objects.create(first_name="Alexandr", last_name="Smetanin")

    Student = apps.get_model("data", "Student")
    student_1 = Student.objects.create(first_name="Roman", last_name="Petrov")
    student_2 = Student.objects.create(first_name="Lev", last_name="Sokolov")
    student_3 = Student.objects.create(first_name="Ivan", last_name="Ivanov")

    HomeWork = apps.get_model("data", "HomeWork")
    hw_1 = HomeWork.objects.create(text="Learn OOP", deadline=10, creator=teacher_1)
    hw_2 = HomeWork.objects.create(text="Read docs", deadline=5, creator=teacher_2)

    HomeworkResult = apps.get_model("data", "HomeworkResult")
    HomeworkResult.objects.create(
        author=student_1,
        homework=hw_1,
        solution="Student_1 solution of hw1",
        created="2022-01-05",
    )
    HomeworkResult.objects.create(
        author=student_2,
        homework=hw_1,
        solution="Student_2 solution of hw1",
        created="2023-01-05",
    )
    HomeworkResult.objects.create(
        author=student_3,
        homework=hw_2,
        solution="Student_3 solution of hw2",
        created="2022-01-06",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_db),
    ]
